/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yoursway_utils_SystemUtilitiesImpl */

#ifndef _Included_com_yoursway_utils_SystemUtilitiesImpl
#define _Included_com_yoursway_utils_SystemUtilitiesImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yoursway_utils_SystemUtilitiesImpl
 * Method:    isConsoleApplication
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_yoursway_utils_SystemUtilitiesImpl_isConsoleApplication
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_yoursway_utils_SystemUtilitiesImpl
 * Method:    getMyDocumentsLocation0
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yoursway_utils_SystemUtilitiesImpl_getMyDocumentsLocation0
  (JNIEnv *, jobject);

/*
 * Class:     com_yoursway_utils_SystemUtilitiesImpl
 * Method:    getProgramFilesLocation0
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yoursway_utils_SystemUtilitiesImpl_getProgramFilesLocation0
  (JNIEnv *, jobject);

/*
 * Class:     com_yoursway_utils_SystemUtilitiesImpl
 * Method:    getApplicationDataLocation0
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yoursway_utils_SystemUtilitiesImpl_getApplicationDataLocation0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
