/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yoursway_swt_experiments_MacOS */

#ifndef _Included_com_yoursway_swt_experiments_MacOS
#define _Included_com_yoursway_swt_experiments_MacOS
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_com_yoursway_swt_experiments_MacOS_OpenDrawer
  (JNIEnv *, jclass, jint, jint, jboolean);

JNIEXPORT jint JNICALL Java_com_yoursway_swt_experiments_MacOS_SetDrawerParent
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
